### ISSUE TITLE
Suggestions for string changes

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webliteracymap#11]
"Exporting and backing up your data from web services"
Should "from" not be "with" or "using" or something ?
I found it in weblitstandard ressource on Transifex.

**Comment by scootergrisen** [comment]
"Using CSS tags to change the style and layout of a Web page".
Is CSS tags correct ?

**Comment by scootergrisen** [comment]
"Using synchronous and asynchronous tools to communicate with Web communities, networks and groups"

Change "Web" til "web":
"Using synchronous and asynchronous tools to communicate with web communities, networks and groups"

To match the other string on Transifex. Or the other way around so all string are using either "Web" or "web".

**Comment by dajbelshaw** [comment]
Thanks @scootergrisen! The canonical URL is https://webmaker.org/literacy

1. I think the idea behind the exporting data example was that people should be encouraged to have a backup of stuff they put online - often in silos.

2. Agreed - we should change this to 'CSS properties'

3. We should definitely be consistent on 'Web/web'. Thanks!

**Comment by dajbelshaw** [comment]
Closing this in favour of issue #19
