### ISSUE TITLE
Create skills underpinning re-scoped 'Web Mechanics' competency

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#14]
We decided on the [29th January community call](http://webliteracy.tumblr.com/post/109569896329/weblitmap-29jan) to merge Infrastructure and Web Mechanics. This has been reflected in the repo (#10). Now we need to come up with the skills for this **new, re-scoped Web Mechanics** competency.

For reference, v1.1:
* [Infrastructure](https://webmaker.org/en-US/resources/literacy/weblit-Infrastructure)
* [Web Mechanics](https://webmaker.org/en-US/resources/literacy/weblit-WebMechanics)

**Comment by dajbelshaw** [comment]
Worth also noting that on the call we also briefly touched on whether we should call this **Web Mechanics** or something else? Basically, we're interested in teaching people the nuts and bolts of how the Web works.

**Comment by jgmac1106** [comment]
There seems to be a clear dilineation between the two being understanding the Web and understanding the Internet.

This will need to be rectified first. We have to encapsulate both the web and the intenet skills under web mechanics. I will play around for a bit. How does that work? Can I just leave comments here or does that mean doing a "pull request?"

**Comment by jgmac1106** [comment]
**Web Mechanics**
*Understand how the Web and internet Work*

- Explaining the differences between the web and the Internet 
- Using and understanding the differences between URLs, IP addresses, and search terms
- Understanding and Labeling the web stack 

** Move **
- "Export and back up your data from the Web" to security
- "Moving the places to where your **content (not data)** is hosted" to composing

** Delete **
- Managing information from various sources on the web (Important but has nothing to do with understanding the web).
- Demonstrating the difference between the results of varying search strategies (redundant with skills under the Search competency).

**Comment by jgmac1106** [comment]
Scratch the move of moving the places where your data is hosted. That is clearly necessary for an understanding of web mechanics. My final list:

**Web Mechanics**
*Understand how the Web and internet Work*

- Explaining the differences between the web and the Internet
- Using and understanding the differences between URLs, IP addresses, and search terms
- Understanding and Labeling the web stack
- Moving the places to where your content  data is hosted

**Comment by dajbelshaw** [comment]
Awesome, thanks @jgmac1106 - look forward to getting additional ideas!

Oh, and pro tip - you can go back and edit comments ad infinitum...

**Comment by dajbelshaw** [comment]
On this week's community call we hacked on the skills underpinning this competency. We ended up with the following:

* Explaining the role of automated systems (including bots) in creating, managing, etc content on the web
* Creating or modifying an algorithm to serve content from around the web
* Identifying where your data is in the network of devices that makes up the Internet, and whether it’s at rest or in motion
* Exporting, moving, and backing up your data from web services
* Using and understanding the differences between URLs, IP addresses and search terms

What's people's thoughts on this?

**Comment by jgmac1106** [comment]
- Explaining the role of automated systems (including bots) in creating, managing, etc content on the web
- Creating or modifying an algorithm to serve content from around the web
- Identifying where your data is in the network of devices that makes up the Internet, and whether it’s at rest or in motion
- Exporting, moving, and backing up your data from web services
- Using and understanding the differences between URLs, IP addresses and search terms

We really bumped up the complexity of this issue. I would lead with the URLs.

**Comment by dajbelshaw** [comment]
Yep, that's because it's merged with **Infrastructure**!

**Comment by jamiea** [comment]
Agree that it's (had to) become more complex, though overall it looks a good step in the right direction for 1.5. Nice deft suggestion @jgmac1106 to put the URL's bullet at the top, really eases the flow.
Unsure about the lack of reference to the practicalities of 'governance' http://en.wikipedia.org/wiki/Internet_governance.
(Interestingly there's no wiki for 'Web Mechanics'!)

**Comment by jgmac1106** [comment]
- Explaining the role of automated systems (including bots) in creating, managing, etc content on the web

Does it make more sense to revise the first one to:
**Explaining the role algorithms play in creating, managing, etc content on the web.**

This way it feeds right into the next skill. 

Is it technically true? Are all bots really algorithms? I think we should capture how shaped the information space is for readers.

**Comment by dajbelshaw** [comment]
OK, great work so far. We've got:

- Using and understanding the differences between URLs, IP addresses and search terms
- Explaining the role algorithms play in creating, managing, etc content on the web.
- Creating or modifying an algorithm to serve content from around the web
- Identifying where your data is in the network of devices that makes up the Internet, and whether it’s at rest or in motion
- Exporting, moving, and backing up your data from web services

I'm not sure about the *at rest / in motion* part of this at the moment. I like the idea of knowing where your data resides - indeed in the multiple places it could reside - but the 'motion' part feels problematic.

Thanks @jgmac1106 & @jamiea for your help so far! :)

**Comment by dajbelshaw** [comment]
Closing this in favour of issue #19
