### ISSUE TITLE
Review all of the skills for v1.5 of the Web Literacy Map

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#19]
![Draft Web Literacy Map v1.5 skills](https://i.imgur.com/D2GMZcI.png)

This is our focus for the February 12th community call: https://teach.etherpad.mozilla.org/weblitmap-12feb15

Here's the epic spreadsheet for comments, etc. http://goo.gl/R1tjj3

**Comment by jamiea** [comment]
Thanks, nice work.
I'm thinking about linking the competencies and skills with occupations & this is a really helpful layout to work from.

**Comment by dajbelshaw** [comment]
Some changes suggested by @scootergrisen in #11

**Comment by dajbelshaw** [comment]
**Update:** Lots of comments added after [yesterday's community call](https://teach.etherpad.mozilla.org/weblitmap-12feb15).

**Comment by dajbelshaw** [comment]
**Meta-level thought:** up until now, we've tried not to 'age' the Web Literacy Map by tying it to particular trends and technologies. However, if we're planning to continually update, does this matter?

A case in point is 'responsive design'. I think a lot of us share the feeling that this is a term that might seem out of date by 2016/17, but might be useful to include now.

Thoughts?

**Comment by stretchyboy** [comment]
I'm not against using a technical term that may date if it gets to the heart of the competency, but if there is a phrase which explains the problem the term solves that might be better.

I'm being a little dense this morning and can't actually find the reference to "responsive design" in the spreadsheet, but I'd say that something like :- 
  "a design that can respond to the dimensions of different devices it may be accessed on so it is accessible"  or ..
  "CSS & HTML which ensures users of all devices can see the content clearly". 

As those define the problem space not the current technique.

**Comment by jamiea** [comment]
Hello folks

Thought I'd add this after reading Thursday's etherpad.

I put links to the Web literacy page on various Wikipedia articles related to the competencies.
The exceptions were for Sharing, Collaboration & Open Practices. Agreed with today's call comments about the first two as too similar (as to make both slightly vague). Most of reading I did around 'sharing' put the idea under the umbrella of open practices, making me question the current scope of that competency. So I'm personally happy to see Sharing go, though preferably blended into Open Practices.

Incidentally, responsive design (along with accessibility issues) was frequently seen from a 'user-centric design' perspective. User-centric design reminded me of both @cassiemc's comments about UX & @sometimesmotion's references to universal design & I wondered if there's anything to be gained by considering the concept of user-centric design for inclusion somewhere.

**Comment by dajbelshaw** [comment]
Thanks @jamiea and @stretchyboy, useful stuff! FYI the 'responsive design' conversation happened on one of the calls and (I think) is recorded in one of the comments on the spreadsheet!

Listening back to last week's call (expertly led by Ian in my absence) there were some fascinating points about the **Connecting** strand. My first reaction is that we should probably think about what constitutes a v1.5 iteration as opposed to something we can return to for v2.0. :)

**Comment by dajbelshaw** [comment]
Note that in preparation for today's community call I've added a **REFINE** tab to the bottom of the spreadsheet: http://goo.gl/R1tjj3

For the benefit of those who can't make the call, here's what I suggest we do with that new tab:

1. Go through comments on **REVIEW** tab at http://goo.gl/R1tjj3
2. Agree on existing skills that we're happy with
3. Move those existing skills to the **REFINE** tab
4. Discuss gaps and agree on (some) new skills for v1.5

**Comment by jgmac1106** [comment]
How do people feel about the idea that if it has no comment, the consensus is we are happy with the skill and we can move it to **REFINE**?

This may save some initial time.

Granted a change on a commented skill may affect one we move but at least we can dig into proposed new skills, proposed collapsed, and proposed revised skills.

Are we still hoping to ship v 1.5 in March?

**Comment by dajbelshaw** [comment]
> How do people feel about the idea that if it has no comment, the consensus is we are happy with the skill and we can move it to **REFINE**?

Read my mind! That's what I was going to suggest on the call. :)

> Are we still hoping to ship v 1.5 in March?

Yep.

I'm also going to propose that further changes to *competencies* should be punted to v2.0 so we can dig into the *skills* over the next couple of weeks. It was those that suffered last time, so it would be good to be happier with them for v1.5.

**Comment by jgmac1106** [comment]
I agree. It also seems to fit the "vibe" of a partial rather than full version update.

**Comment by jgmac1106** [comment]
Can we use git in between calls? to get some agreement work done before the calls each week? or is better to wait for the call?

Maybe we could do a suggested change: "I propose "skill" in cell "X" ** Review** be changed to "skill" in cell "Y" on **Refine**

We could either put a waiting period on it or just have a firm list to discuss during each conference call.

I just worry about the timeline so we make our deliverable target. We finalized four skills and one competency during last call....though we won't have to discuss the major connecting overhaul we will undertake in V 2 so we will have more time next week.

**Comment by dajbelshaw** [comment]
Yes of course @jgmac1106! Just start a new issue for the relevant competency. :)

**Comment by jgmac1106** [comment]
So three new issues? One for each competency?

**Comment by dajbelshaw** [comment]
Closing this in favor of issue #36
