### ISSUE TITLE
Define skills under 'Navigation' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#21]
**Navigation** 
*Using software tools to browse the web*

- Accessing the web using the common features of a browser
- Using hyperlinks to access a range of resources on the web
- Reading, evaluating, and manipulating URLs
- Recognizing the common visual cues in web services
- Exploring browser add-ons and extensions to provide additional functionality

------
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
There was no issue with 

- accessing the web using the common features of a browser

There was a call for clarifying:
-Recognizing the visual cues in everyday web services
This was called ambiguous and some felt it made add-ons and extensions sound essential
- Using browser add-ons and extensions to provide additional functionality

Any ideas?

**Comment by xellpher** [comment]
I see no issue with the second one. As with many issues here, it is elaborated in the club activity. Take a look at Kraken the code [tip sheet] (https://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/legit-o-meter.html), where it is connected with search and reliability. Overlapping once more...

How about removing the "everyday"? Visual cues exist in all services and websites, and they should be noted.

**Comment by jgmac1106** [comment]
Visual cues are also more important in mobile v desktop browsing. I can use my menu bars and website meus. 

I'd hate to say navigational cues so maybe just removibg everyday makes sense.

**Comment by gaditb** [comment]
By "everyday" do we just mean "common"? Like, common patterns used in UI? (Links are blue and/or underlined, hamburger menu (is this too just-now, not-yet-definitely-gonna-stick? I have limited sense of time or awareness), tabs provides different view or different content that can be switched back and forth... (not an exhaustive or a prioritized list))

**Comment by dajbelshaw** [comment]
Thanks @jgmac1106 - have (re-)added *accessing the web using the common features of a browser* to the REFINE tab and at the top of this issue.

Thanks for pointing out the problem with 'everyday', @xellpher. I like @gaditb's suggestion that we go with 'common'. How about the following?

* Recognizing the common visual cues in web services

In terms of the other one, we could change it to:

* Exploring browser add-ons and extensions to provide additional functionality

Thoughts? :)

**Comment by jgmac1106** [comment]
Final:

- Accessing the web using the common features of a browser
- Using hyperlinks to access a range of resources on the web
- Reading, evaluating, and manipulating URLs
- Recognizing the common visual cues in web services
- Exploring browser add-ons and extensions to provide additional functionality

**Comment by dajbelshaw** [comment]
Updated first comment and marked as done!
