### ISSUE TITLE
Define skills under 'Web Mechanics' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#22]
**Web Mechanics** 
*Understanding the web ecosystem and Internet stack*

* Explaining the role algorithms play in creating, managing, etc content on the web.
* Creating or modifying an algorithm to serve content from around the web
* Identifying where your data is in the network of devices that makes up the Internet, and whether it’s at rest or in motion
* Exporting, moving, and backing up your data from web services
* TBD

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
There was a question if these three terms should be separated and what learners need to know about the difference between the three:

- Using and understanding the differences between URLs, IP addresses and search terms

**Comment by gaditb** [comment]
All three are definitely confused standardly. My grandmother, for example, when you gave her a URL, would go to Google, type it into the search bar, and click the top link. (She... might have gotten better at it. I'm not sure.) It's common to give directions to a web site as "just search <stuff> and click the top link". 

IP addresses should be included with these, because it's too small for "what is an IP address" to be it's own thing (there's enough for a full section on IP addresses if you include networks and network masks and stuff, but... no. That's not basic literacy.), they're a very easy concept to grasp ("Street Address"), and they mesh well with explaining what URLs are.

They should be kept together, and the main point of the skill should be explaining what a URL is, as opposed to search terms, and also ending with "and this is what an IP address, too".

**Comment by dajbelshaw** [comment]
@jgmac1106: I think it's the differences *between* these that are important - which is what @gaditb has said more eloquently than me! :)

**Comment by jgmac1106** [comment]
Leave as is then if Marc is okay. He posted the question.

**Comment by jgmac1106** [comment]
- Using and understanding the differences between URLs, IP addresses and search terms (needs approval) 
- Explaining the role algorithms play in creating, managing, etc content on the web.(approved)
- Creating or modifying an algorithm to serve content from around the web (approved)
- Identifying where your data is in the network of devices that makes up the Internet, and whether it’s at rest or in motion (approved)
- Exporting, moving, and backing up your data from web services (approved)

**Comment by jgmac1106** [comment]
Final:

- Using and understanding the differences between URLs, IP addresses and search terms 
- Explaining the role algorithms play in creating, managing, etc content on the web.
- Creating or modifying an algorithm to serve content from around the web.
- Identifying where your data is in the network of devices that makes up the Internet, and whether it’s at rest or in motion.
- Exporting, moving, and backing up your data from web services.

**Comment by dajbelshaw** [comment]
Making some small changes to this:

- **Explaining the role algorithms play in creating, managing,** <s>etc</s> **content on the web.**
- **Identifying where data is in the network of devices that makes up the Internet**<s>, and whether it’s at rest or in motion.</s>
- **Exporting, moving, and backing up** <s>your</s> **data from web services.**

**Comment by gaditb** [comment]
Ordering:
Maybe move "Identifying where your data is" and "moving your data" up to 2nd and 3rd positions, respectively?

That keeps "Identifying major components" at the top (do we want "explaining algorithms" to maybe be in the top three as well? I'm not sure, but if so I'd say 3rd), and has the first active skill be the more commonly used one.

**Comment by jamiea** [comment]
+1 @gaditb

**Comment by dajbelshaw** [comment]
Great suggestion! Updated. :)

Oh, and @gaditb: would love to credit your contributions [here](https://github.com/mozilla/webliteracymap/blob/master/Contributors.md) if you want to share your full name?

**Comment by gaditb** [comment]
Oh! Thank you -- um, are psudonyms/not-meatland identities okay? "Gadit Bielman".

**Comment by dajbelshaw** [comment]
Oh yes, you're absolutely fine to choose to be pseudonymous. You choose. 

Apologies, shouldn't have mentioned 'full name'. :)

**Comment by gaditb** [comment]
Well, I mean, could you put it as "Gadit Bielman" in full? That was the pseudonym I was asking about.

**Comment by dajbelshaw** [comment]
Oh yes, no problem - done!

https://github.com/mozilla/webliteracymap/blob/master/Contributors.md
