### ISSUE TITLE
Define skills under 'Credibility' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#24]
**Credibility** 
*Critically evaluating information found on the web*

* Comparing and contrasting information from a number of sources. 
* Making judgments based on technical and design characteristics.
* Discriminating between 'original' and derivative web content.
* Identifying and investigating the author or publisher of web resources.
* Evaluating how purpose and perspectives shape web resources.

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
I would like to add:

*Investigating the author or publisher of web resources*


This could be worded as

*Judging the author or publisher of web resources*

We need to be explicit about judging the expertise, bias, and perspectives of author/publisher but I think we can capture all three in one skill.

**Comment by dajbelshaw** [comment]
Nice, @jgmac1106! To make this different from the others, we could have:

* Ascertaining the author of publisher of web resources

In addition, I think the first two skills we've identified are two wordy. How about we chop them down to the following?

* Making judgments based on technical and design characteristics
* Comparing and contrasting information from a number of sources

**Comment by jgmac1106** [comment]
Ascertaining means just identifying correct? We need them to more than just identify. 

*evaluating? *

**Comment by jgmac1106** [comment]
Decision points needed on:

Revising the first two to:
- Making judgments based on technical and design characteristics
- Comparing and contrasting information from a number of sources

Adding and finalizing wording on:

- Ascertaining the author or publisher of web resources

There was also a question on the spreadsheet of: 

- Do we need an an evaluation of currency skill?

**Comment by dajbelshaw** [comment]
Agree with @jgmac1106 that 'Identifying' is better than the somewhat-pretentious 'Ascertaining' ;)

I'm not sure what this question means: *Do we need an an evaluation of currency skill?*

**Comment by jgmac1106** [comment]
That was the comment from the gSheet. Looking at publication date.

**Comment by jgmac1106** [comment]
I am saying we need to go deeper then "identifying" if we leave it as identify you have mastered the skil when you can find the author.

Either:

- Identifying and evaluating the author or publisher of web resources.
- Evaluating the author or publisher web resources.

**Comment by jgmac1106** [comment]
Approved: 
- Comparing and contrasting information from a number of sources. 
- Making judgments based on technical and design characteristics.  
- Discriminating between 'original' and derivative web content.

Under review:
- Identifying  the author or publisher of web resources (Doug)
- Researching the  ownership of websites and their content

Proposed:
- A question about currency (publication date).

**Comment by xellpher** [comment]
I'll again refer to the [Kraken the Code tip list] (https://docs.google.com/file/d/0ByDhuNZWuJn-bmdaTkoxeDZ4Vmc/edit) of what to look for when determining the reliability of a website. Kraken is a tested and approved activity for the clubs. I think the competency should reflect the skill.

The list above by @jgmac1106 covers everything except **design, domain, and sale** from the tip sheet. How about including:
* Finding out the differences between domains
* Researching the ownership, content and design of websites in relation to what the site wants to achieve

The difficulty, I suppose, is to make an exercise that determines the criteria for a website that is 'trying to make a sale'

**Comment by dajbelshaw** [comment]
Thanks @xellpher! To refine the first one, how about:

* Comparing and contrasting differences between types of domain names and URL structures

I'm not sure the second wone is necessary given the other skills? I may be wrong.

**Comment by jgmac1106** [comment]
I don't think "sale"  is that important I think evaluating purpose and
perspectives matter. Turning a profit is just one.

**Comment by dajbelshaw** [comment]
Updated the first three skills, per decision on this week's community call.

**Comment by jgmac1106** [comment]
These two while different are similar and could be collapsed:

- Identifying the author or publisher of web resources.
- Researching the ownership of websites and their content

How about 
- Researching the author and publisher of web resources.
-Examining how purpose and perspectives shape web resources

I would leave out examining the url. We have that under web mechanics and while it is a skill often taught  (Like in Kraken) it often leads to errors of oversimiplification, "It is a .org so it must be true."

We can included surface level markers but I would argue your url is a "technical characteristic" and already covered by the second skill.

**Comment by dajbelshaw** [comment]
Thanks @jgmac1106, definitely take your point about URLs being taken on face value. However, I'd argue that there's still value in looking at the URL when determining the credibility of the information presented on a web page.

The trouble with verbs such as *"researching"*, *"examining"*, and *"finding out"* is that they're either a) inherently 'wooly' or, b) become vague when applied to the current educational landscape.

I think we get to where we want to be through these four:

- Comparing and contrasting information from a number of sources
- Making judgments based on technical and design characteristics
- Discriminating between 'original' and derivative web content
- Identifying  the author or publisher of web resources

What do others think? I don't want to rush this, but also recognise we're bumping up against a deadline here.

**Comment by jgmac1106** [comment]
I could see how purpose and perspectives to get at @xellpher goal could be included in author and publisher. I would be fine with those four if the learner has to do more than simply identify the author. He want her to consider *expertise* *goals* and *perspectives* As written you master the skill when you say, "Doug wrote this."

So if we go with four I would say change "Identifying" to "Evaluating."

If we go with five it is:

- Identifying the author or publisher of web resources
- Evaluating (or discussing)how purpose and perspectives shape web resources.

**Comment by dajbelshaw** [comment]
<3 the change from *"Identifying"* to *"Evaluating"* - moves it up Bloom's Taxonomy nicely. :)

**Comment by dajbelshaw** [comment]
Updated first comment with defined skills from 17th March half-hour hack call. Closing this!
