### ISSUE TITLE
Define skills under 'Security' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#25]
**Security** 
*Keeping systems, identities, and content safe*

* Recommending how to avoid online scams and 'phishing'
* Managing and maintaining account security
* Encrypting data and communications using software and add-ons
* Changing the default behavior of websites, add-ons and extensions to make web browsing more secure

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
There was a question about:

- Changing the default behavior of websites, add-ons and extensions to make web browsing more secure

Suggested rewrites for this skill included:
- reducing risk of external threats by choosing suitable add-ons . OR 
- choosing between convenience and protection.

**Comment by jgmac1106** [comment]
There were three comments asking for a skill about protecting personal identity. Some argued identity should fit under privacy and security should be system specific.

**Comment by dajbelshaw** [comment]
*Updated competency descriptor as I'd copied/pasted incorrectly!*

I think this works:

* Changing the default behavior of websites, add-ons and extensions to make web browsing more secure

Not so keen on the (false?) dichotomy between *'convenience and protection'*. Mitigating external threats through changing practices seems like something to address somehow.

**Comment by xellpher** [comment]
Where do strong passwords belong? Wasn't there a mention about them earlier?

**Comment by gaditb** [comment]
Honestly, do we want "mitigating external threats trough changing practices" to be it's own skill just like that? That doesn't seem like that bad phrasing.

Or maybe two: "Identifying risky or insecure practices" and "Limiting, eliminating, and containing risky or insecure practices" (the verbs should probably be rephrased).

And like I'd like to -- maybe not emphasize, but at least explicitly address throughout, the fact that there often *is* a tradeoff between "convenience" and "protection".
And it's not a constant thing -- some activities are more like Jaywalking-Or-Not (e.g. signing up and logging in to a small, I-will-use-this-like-once web service/forum over HTTP), some are more like Not-Playing-On-Railroad-Tracks (don't run random stuff from the internet), some are more like Washing-Hands (using unique passwords -- takes extra time, requires deliberate setup/tools, can be done to greater or lesser completeness, but useful and should be used everywhere and important)

And we need to acknowledge that. If we just tell people "don't play on the railroad tracks" in the same voice as "don't jaywalk", they're just gonna do both.

**Comment by dajbelshaw** [comment]
Added the following after today's half-hour hack meeting:

* Changing the default behavior of websites, add-ons and extensions to make web browsing more secure

Definitely need something more broad than 'strong passwords' as well! :)

**Comment by sometimesmotion** [comment]
I'm not so sure about 'ensuring' - it's difficult to assess if someone has 'ensured' the security of their account. Additionally, there is no point at which someone can sit back and say 'job done!' about securing their account/data- it's an evolving threat. How about a verb that implies continued management/vigilance: 
* Managing and maintaining account security.

**Comment by jgmac1106** [comment]
I like maintaining as well.

**Comment by xellpher** [comment]
I like the suggestion by @sometimesmotion 

This is what I was talking about yesterday, from the [privacy badge deliverable] (https://docs.google.com/document/d/1h96ccZsTxBBAgyGMsNMfR_h7rtR1fJaHcosMyGuzYvM/edit?pli=1#):

Explaining ways in which computer criminals are able to gain access to user information
Name: Privacy: Passwords

Description: The ‘Privacy: Passwords’ badge is earned by those who want to find ways to create stronger passwords and keep track of them. This includes using services that securely manage and save unique passwords.

Criteria: 
Link to an example of a computer criminal getting access to user information through weak passwords
Describe motivations that computer criminals have for stealing personal information
Change your passwords to stronger, unique ones (e.g. using LastPass / 1Password) and/or utilize two-factor authentication.

**Comment by xellpher** [comment]
What Roz talked about yesterday is also there in skill number 5: Identifying and taking steps to keep important elements of identity private

Should that be added her as well?

**Comment by xellpher** [comment]
To answer myself: I think "Identifying important elements of identity" belongs in privacy, whereas the locks on the door "Managing and maintaining account security" belongs here.

**Comment by dajbelshaw** [comment]
OK, adding the following as agreed upon:

* Managing and maintaining account security

We're at four skills now under **Security**. Do we need a fifth, or is this ready to be closed?

**Comment by jgmac1106** [comment]
I am okay with four. Though I wonder  if passwords belong under security and not privacy. We seem to badging under assumption that passwords are part of privacy.

**Comment by jgmac1106** [comment]
If we move computer criminal skill over from privacy I would be okay with no password skill as these would be redundant.

**Comment by dajbelshaw** [comment]
>  We seem to badging under assumption that passwords are part of privacy. 

We created badges according to Web Literacy Map v1.1. I don't think we need be limited by that - particularly given the addition discussion and layers of nuance we've identified between **Security** and **Privacy**. 

These are the four we've decided upon. I reckon passwords are firmly within the realm of 'putting locks on your doors' (i.e. **Security**) rather than 'curtains on your windows' (i.e. **Privacy**). We'll run with the following for v1.5 unless anyone throws a Hail Mary in the dying seconds:

* Detecting online scams and 'phishing' by employing recognized tools and techniques
* Encrypting data and communications using software and add-ons
* Changing the default behavior of websites, add-ons and extensions to make web browsing more secure
* Managing and maintaining account security

**Comment by jamiea** [comment]
" Detecting online scams etc." seems a bit higher level to me.
How about exchanging the verbs for this skill to make it more accessible:

* _Recognising_ online scams and 'phishing' by employing _detection_ tools and techniques

**Comment by dajbelshaw** [comment]
See where you're coming from, @jamiea but 'detecting' seems to be a bit more front-foot and *active* than 'recognising'.

What do others think? :)

**Comment by jamiea** [comment]
Agreed, though the amount & level of activity required can perhaps be gleaned from the excellent http://honeynet.org/about project. Check out the papers in the right hand aside.

(Scary project map here, leave it open in the tab! http://map.honeynet.org/  )

**Comment by jgmac1106** [comment]
Can you detect a scam without an actual attack? How would clubs teach this
skill?

**Comment by jamiea** [comment]
If there's no safe 'dummy' open learning materials for this out there, other than by using real-world examples personally I didn't see how else one can *detect* a scam.  Genuine detection seems like a risky business requiring what I'd consider to be a high level of pre-existing resources and knowledge to conduct a secure investigation that reaches accurate conclusions.

**Comment by jgmac1106** [comment]
Agree. Its why I lean away from word detecting and think explaining or
analyzing (bloom bump)  works better.

**Comment by jamiea** [comment]
+1 Analyzing 

and a nice appropriate definition in Bloom's that IMO seems to satisfy some of the necessary pre-requisites of 'detecting'

**Comment by dajbelshaw** [comment]
Hmmm... so the problem we've got with all of the verbs that we've proposed here *(detecting / recognizing / analyzing)* is that they pre-suppose, to a greater or lesser degree, that an attack is currently taking place:

How about:

* Recommend ways users can avoid online scams and 'phishing' 

Still not quite right, but how about the direction of travel? :)

**Comment by sometimesmotion** [comment]
+1 
I like the new phrasing - it's more concrete and obvious as a goal/outcome. I think this makes it more useful for the clubs.
We've been using the -ing tense so: 

* Recommending how to avoid online scams and 'phishing'

**Comment by dajbelshaw** [comment]
Oops! +1 (thanks @sometimesmotion)

**Comment by jgmac1106** [comment]
+1

**Comment by dajbelshaw** [comment]
OK, so unless I hear otherwise, we're going with:

* Detecting online scams and 'phishing' by employing recognized tools and techniques
* Encrypting data and communications using software and add-ons
* Changing the default behavior of websites, add-ons and extensions to make web browsing more secure
* Managing and maintaining account security
* Recommending how to avoid online scams and 'phishing'

Any thoughts on preferred ordering? :)

**Comment by jamiea** [comment]
Wasn't that going to be:
Recommending how to avoid online scams and 'phishing'

Date: Thu, 19 Mar 2015 14:45:10 -0700

**Comment by sometimesmotion** [comment]
Yes- get rid of 'Detecting online scams...' and I feel good about these. The order isn't so important from my point of view. There's no clear hierarchy with these.

**Comment by jgmac1106** [comment]
I am good.

**Comment by gaditb** [comment]
I'd go for:
- Phishing/Scams
- Account Security
- Encrypting
- Addons

While there isn't a hierarchy, I feel like that puts it in order of both importance and ease/amount of work. If people get bored/scared off after the first two, I want to to be those.

**Comment by dajbelshaw** [comment]
Oops. Sorry about that. So, per @gaditb's suggestion, the order for these skills would be: 

* Recommending how to avoid online scams and 'phishing'
* Managing and maintaining account security
* Encrypting data and communications using software and add-ons
* Changing the default behavior of websites, add-ons and extensions to make web browsing more secure

We've 6 hours to decide whether we're OK with that. **+1** from me!

**Comment by jamiea** [comment]
+1

**Comment by dajbelshaw** [comment]
Right, closing this and updating overview. Comment to re-open if you've any objections!

![batman - thumbs up](https://cloud.githubusercontent.com/assets/2429426/6752855/9204a2ee-cf09-11e4-84b2-53c807d4eeb5.gif)
