### ISSUE TITLE
Define skills under 'Composing for the web' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#26]
**Composing for the web** 
*Creating and curating content for the web*

* Inserting hyperlinks into a web page
* Embedding multimedia content into a web page
* Creating web resources in ways appropriate to the medium/genre
* Identifying and using HTML tags
* TBD

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
We should  add:

**Creating your own space to publish on the Web.**

**Comment by dajbelshaw** [comment]
Interesting, @jgmac1106 - especially as this is under the **Building** strand. It certainly appears to fit in here (and you *know* I'm in favour of the sentiment). Just wondering if others think this is in-scope for this particular competency? 

I'm happy to add it in if others are! :)

**Comment by xellpher** [comment]
I think it's a great idea. How about leaving the publishing out: **Creating your own space on the Web.** This would include not just the tools for building, but also for searching and the other bits and bobs. Talk about out-of-scope... :)

I certainly would benefit from having a blueprint of the space I occupy on the web. (I'm already drawing a map in my head.)

In any case, I think it should definitely be included. Brings an agency to the project, having an idea about the tools one uses.

**Comment by xellpher** [comment]
This could be something like your [workflow] (http://dougbelshaw.com/blog/2015/02/05/my-current-workflow/) post @dajbelshaw but with **everything** included :)

**Comment by dajbelshaw** [comment]
Thanks @xellpher! How about something about the notion of 'control'? Perhaps:

* Creating and controlling a space to publish on the Web

Not perfect, but I think the 'publishing' part ties it to this competency, while the 'controlling' makes it more than just having a Facebook page.

Thoughts? :)

**Comment by jgmac1106** [comment]
I dig it.

**Comment by dajbelshaw** [comment]
> I dig it.

Great! Let's finalise on the call this week. We'll have five skills at that point, which probably means we can tick off **Composing for the Web** as done. :)

**Comment by jgmac1106** [comment]
Final List:

- Inserting hyperlinks into a web page.
- Embedding multimedia content into a web page.
- Creating web resources in ways appropriate to the medium/genre .
- Identifying and using HTML tags.
- Setting up and controlling a space to publish on the Web.

**Comment by dajbelshaw** [comment]
Great stuff. Have updated the first comment. :)
