### ISSUE TITLE
Define skills under 'Designing for the web' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#28]
**Designing for the web** 
*Enhancing visual aesthetics and user experiences*

* Using CSS properties to change the style and layout of a Web page
* Demonstrating the difference between inline, embedded and external CSS
* Improving user experiences through feedback and iteration
* Creating device-agnostic web resources
* TBD

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
Final
- Using CSS properties to change the style and layout of a Web page
- Demonstrating the difference between inline, embedded and external CSS
- Improving user experiences through feedback and iteration
- Creating device-agnostic web resources

**Comment by dajbelshaw** [comment]
\o/
