### ISSUE TITLE
Define skills under 'Accessibility' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#30]
**Accessibility** 
*Communicating in a universally-recognisable way*

* Using empathy and awareness to inform the design of web content that is accessible to all users
* Designing for different cultures which may have different interpretations of design elements
* Comparing and exploring how different interfaces impact diverse users
* Improving the accessibility of a web page through the design of its color scheme, structure/hierarchy and markup
* Comparing and contrasting how different interfaces impact diverse web users

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
Everyone agreed last week to add:

- Reorganizing the structure of a web page to improve its hierarchy/ conceptual flow

**Comment by jgmac1106** [comment]
Final

- Using empathy and awareness to inform the design of web content that is accessible to all users
- Designing for different cultures which may have different interpretations of design elements
- Comparing and exploring how different interfaces impact diverse users
- Improving the accessibility of a web page through the design of its color scheme, structure/hierarchy and markup
- Reorganizing the structure of a web page to improve its hierarchy/ conceptual flow

**Comment by dajbelshaw** [comment]
These feel along the right lines, but are perhaps little wordy. How about: 

- Using empathy and awareness to inform the design of universally-accessible web content
- Designing for different cultures and interpretations 
- Comparing and contrasting how different interfaces impact the full spectrum of web users
- Improving the accessibility of a web page through the design of its color scheme, structure/hierarchy and markup
- Reorganizing the structure of a web page to improve its hierarchy/ conceptual flow

**Comment by jgmac1106** [comment]
I like diverse better than full spectrum.

**Comment by dajbelshaw** [comment]
OK, how about:

* Comparing and contrasting how different interfaces impact diverse web users

**Comment by dajbelshaw** [comment]
Marked resolved after [half-hour hack call](https://teach.etherpad.mozilla.org/weblitmap-17mar15) today. Well done everyone!
