### ISSUE TITLE
Define skills under 'Collaborating' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#32]
**Collaborating** 
*Creating web resources with others*

* Choosing a Web tool to use for a particular contribution/ collaboration
* Co-creating Web resources
* Configuring notifications to keep up-to-date with community spaces and interactions
* Working towards a shared goal using synchronous and asynchronous tools
* Developing and communicating a set of shared expectations and outcomes

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
There was a suggestion to add:

- Working with others while communicating both synchronously and asynchronously

**Comment by dajbelshaw** [comment]
+1

**Comment by jgmac1106** [comment]
+1 myself. Does git have a polling feature in issues?

**Comment by dajbelshaw** [comment]
Need to phrase this carefully, as **Open Practices** has: *"Participating in both synchronous and asynchronous discussions"*

**Comment by jgmac1106** [comment]
Some possible ideas:

- Arriving at a shared goal through synchronous and asynchronous work.
- Monitoring individual and group contributions to ensure efficient work flow.
- Developing a set of shared expectations and outcomes.

**Comment by sometimesmotion** [comment]
I like @jgmac1106's skills above but have a couple of tweaks: 

* Working towards a shared goal using synchronous and asynchronous means/tools.
* Developing and communicating a set of shared expectations and outcomes.
[with 'communicating' I'm trying to get at: making sure that the expectations & outcomes are clear to everyone involved.]

**Comment by jgmac1106** [comment]
I like @sometimesmotion fixes

**Comment by dajbelshaw** [comment]
Good work @jgmac1106 @sometimesmotion. I'd drop 'means' from the first skill but other than that <3 it.

What do others think? Feel free to +1

**Comment by dajbelshaw** [comment]
Done! Wonderful. Thanks to those who attended the [half-hour hack session](https://teach.etherpad.mozilla.org/weblitmap-17mar15) to finish these off. :)
