### ISSUE TITLE
Define skills under 'Community Participation' competency for v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#33]
**Community Participation** 
*Getting involved in web communities and understanding their practices*

* Engaging in web communities at varying levels of activity
* Respecting community norms when expressing opinions in web discussions
* Making sense of different terminology used within online communities
* Participating in both synchronous and asynchronous discussions
* TBD

-----
See spreadsheet at http://goo.gl/R1tjj3

**Comment by dajbelshaw** [comment]
A few suggestions in the comments from the REVIEW tab:

* Engaging in web communities at varying levels of activity. *(Greg)*
* Expressing opinions appropriately with constructive criticism in group or community settings. *(Tim)*
* Defining different terminology used within the discourse of online communities. *(Ian, paraphrased)*
* Participating in both synchronous and asynchronous discussions. *(on reflection, this one was OK)*

**Comment by dajbelshaw** [comment]
I've updated the list of skills after discussion on this week's community call. We have four, do we need another? http://goo.gl/R1tjj3

**Comment by jgmac1106** [comment]
Final:

- Engaging in web communities at varying levels of activity
- Respecting community norms when expressing opinions in web discussions
- Making sense of different terminology used within online communities
- Participating in both synchronous and asynchronous discussions

**Comment by dajbelshaw** [comment]
Great! Updated first comment.
