### ISSUE TITLE
Define all skills for Web Literacy Map v1.5

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/webliteracymap#36]
*Note: this is a meta-issue*

-----

Below is the list of competencies for Web Literacy Map v1.5. We still need to define the skills underpinning these. Clicking on a competency takes you to the relevant issue. Once we're happy that we've defined all of the skills under a competency, it should be ticked-off here!

EXPLORING
* [x] [Navigation](https://github.com/mozilla/webliteracymap/issues/21)
* [x] [Web Mechanics](https://github.com/mozilla/webliteracymap/issues/22)
* [x] [Search](https://github.com/mozilla/webliteracymap/issues/23)
* [x] [Credibility](https://github.com/mozilla/webliteracymap/issues/24)
* [x] [Security](https://github.com/mozilla/webliteracymap/issues/25)

BUILDING
* [x] [Composing for the web](https://github.com/mozilla/webliteracymap/issues/26)
* [x] [Remixing](https://github.com/mozilla/webliteracymap/issues/27) 
* [x] [Designing for the web](https://github.com/mozilla/webliteracymap/issues/28)
* [x] [Coding / Scripting](https://github.com/mozilla/webliteracymap/issues/29)
* [x] [Accessibility](https://github.com/mozilla/webliteracymap/issues/30)

CONNECTING
* [x] [Sharing](https://github.com/mozilla/webliteracymap/issues/31)
* [x] [Collaborating](https://github.com/mozilla/webliteracymap/issues/32)
* [x] [Community Participation](https://github.com/mozilla/webliteracymap/issues/33)
* [x] [Privacy](https://github.com/mozilla/webliteracymap/issues/34)
* [x] [Open Practices](https://github.com/mozilla/webliteracymap/issues/35)

**Comment by jamiea** [comment]
Thanks @dajbelshaw et al, the process behind the Map just get better and better, nice work.

**Comment by dajbelshaw** [comment]
Updated overview above to indicate current progress in preparation for [half-hour hack session on Monday 16th March](https://teach.etherpad.mozilla.org/weblitmap-16mar15)

**Comment by dajbelshaw** [comment]
No community call this week. Instead, half-hour hack sessions on Monday and Tuesday:

* [Monday 16th March](https://teach.etherpad.mozilla.org/weblitmap-16mar15) (5pm UTC)
* [Tuesday 17th March](https://teach.etherpad.mozilla.org/weblitmap-17mar15) (5pm UTC)

We need to finish defining the skills by the end of the week, but you're very welcome to comment and add thoughts here if you can't make the above times!

**Deadline: Friday 20th March (5pm UTC)**

**Comment by dajbelshaw** [comment]
Thanks to those who came to the [16th March](https://teach.etherpad.mozilla.org/weblitmap-16mar15?) half-hour hack session! We managed to complete:

* Credibility
* Remixing

There's still some questions around:

* [Security](https://github.com/mozilla/webliteracymap/issues/25)
* [Coding / Scripting](https://github.com/mozilla/webliteracymap/issues/29)

Let's continue to work on those asynchronously! :)

**Comment by dajbelshaw** [comment]
Great discussion yesterday in the [17th March](https://teach.etherpad.mozilla.org/weblitmap-17mar15) half-hour hack session. Thank you. 

We had a very productive discussion and managed to finalise:

* Accessibility
* Collaborating
* Open Practices

There's still a few questions around:

* [Privacy](https://github.com/mozilla/webliteracymap/issues/34)

...and of course we still haven't tied a bow on:

* [Security](https://github.com/mozilla/webliteracymap/issues/25)
* [Coding / Scripting](https://github.com/mozilla/webliteracymap/issues/29)

I'll have to use my [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) privileges if we don't come to some sort of consensus by Friday! ;)

**Comment by jgmac1106** [comment]
How do we want to handle last three? @dajbelshaw want to put up the final proposed and we vote by end of business his time?

**Comment by dajbelshaw** [comment]
I wasn't actually joking, @jgmac1106 - if we don't come to consensus by about 4pm GMT tomorrow then I'll just go with what I think is the majority line. :)

**Comment by dajbelshaw** [comment]
One more meta-level thing.

If we want to be intentional about the *ordering* of skills within a competency, then we should lock that down by tomorrow, too. Feel free to go back into any competencies and comment if the ordering of skills needs work. No need to re-open issue to comment.

**Comment by jgmac1106** [comment]
I know you weren't joking and I am happy with the skills as is. We are
close on so many issues.

**Comment by dajbelshaw** [comment]
We're finished! w00t! Well done and huge congratulations, everyone. :-D

I've blogged the full list of skills competencies: http://literaci.es/web-literacy-map-v1-5

Please do share your reflections on the process on your blog and share it out with the hashtag #webliteracy! 

![coffee](https://cloud.githubusercontent.com/assets/2429426/6755975/b7495814-cf1e-11e4-9d7a-d681fae8cb88.gif)
